version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.6.2
    network_mode: host
    ports:
      - "2182:2181"
      - "9100:8080"
    volumes:
      - zookeeper-data:/main
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    network_mode: host
    ports:
      - 9090:9090
    restart: always
    environment:
      - "HTTP_PORT=9090"
#  zookeeper:
#    image: zookeeper:3.6.2
#    network_mode: host
#    ports:
#      - "2181:2181"
#    volumes:
#      - zookeeper-data:/main
#  zoonavigator:
#    image: elkozmon/zoonavigator:latest
#    ports:
#      - "9000:9000"
#    restart: always
#    #    container_name: "zoonavigator"
#    #    network_mode: host
#    #    networks:
#    #      - zk-net
#    environment:
#      #      - "HTTP_PORT=9090"
#      #      - "CONNECTION_LOCALZK_NAME=zk-net"
#      #      - "CONNECTION_LOCALZK_CONN=zookeeper"
#      - "AUTO_CONNECT_CONNECTION_STRING=zookeeper:2181"

#      - API_HOST=localhost
#networks:
#  zk-net:
#    external: true
volumes:
  zookeeper-data: