version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.6.2
    network_mode: host
    ports:
      - "2182:2181"
      - "9100:8080"
    volumes:
      - zookeeper-data:/main
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    network_mode: host
    ports:
      - 9090:9090
    restart: always
    environment:
      - "HTTP_PORT=9090"
volumes:
  zookeeper-data:
