spring:
  main:
    web-application-type: reactive
  banner:
    location: logo-ascii.txt
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  security:
    enabled: false
springdoc:
  version: "${VERSION:1.0.0}"
  swagger-ui:
    path: "/"
server:
  port: 2783